[server]
maxUploadSize = 50        # MB — tamanho máximo do CSV
headless = true

[theme]
primaryColor = "#272949"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#EEEEF8"
textColor = "#1E1E2E"
font = "sans serif"

[browser]
gatherUsageStats = false
